###############################################################
# Program:
#     Assignment 04, Product inventory
#     Brother Comeau, CS165
# Author:
#     Denis Lazo
# Summary:
#     This is code that can tell you how much you will pay
#      per item plus shipping and tax
###############################################################


# We will learn fancier compilation steps later, but this is
# good enough for now...
a.out : product.h product.cpp assign04.cpp
	g++ product.cpp assign04.cpp

