###############################################################
# Program:
#     Assignment 05, Order Tracking
#     Brother Comeau, CS165
# Author:
#     Denis Lazo
# Summary:
#     Basically this code has many files in it,
#     it will not only give the product's information
#     but customer and order's information
###############################################################


# We will learn fancier compilation steps later, but this is
# good enough for now...
a.out : product.h product.cpp address.h address.cpp customer.h customer.cpp order.h order.cpp assign05.cpp
	g++ product.cpp address.cpp customer.cpp order.cpp assign05.cpp

